spring:
  jackson:
    serialization:
      write-enums-using-to-string: true
    deserialization:
      read-enums-using-to-string: true
  datasource:
    url: jdbc:mysql://localhost:3307/readdb?useSSL=false&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3306/writedb?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    javax:
      sql: INFO
      persistence: INFO
    org:
      springframework:
        data: INFO
        transaction: INFO
      apache:
        tomcat: INFO