spring:
  datasource:
    url: jdbc:mysql://localhost:3306/writedb?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    serialization:
      write-enums-using-to-string: true
    deserialization:
      read-enums-using-to-string: true
hibernate:
  dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    javax:
      sql: DEBUG
      persistence: DEBUG
    org:
      springframework:
        data: DEBUG
        transaction: DEBUG
      apache:
        tomcat: DEBUG